# base.yaml
database:
  path: "data/market_data.db"
  pool_size: 5
  timeout: 30

trading:
  max_position_size: 0.1  # 10% of portfolio
  max_drawdown: 0.2      # 20% maximum drawdown
  risk_free_rate: 0.02   # 2% risk-free rate
  min_trade_size: 1000
  max_trade_size: 1000000
  trading_hours:
    start: "09:30"
    end: "16:00"
  market_close_buffer: 300  # 5 minutes before market close

risk:
  max_risk_per_trade: 0.02    # 2% per trade
  max_correlation: 0.7        # Maximum correlation between positions
  max_portfolio_heat: 0.8     # Maximum portfolio heat
  position_sizing:
    confidence_factor: 0.2
    volatility_factor: 0.1
  stop_loss:
    atr_multiplier: 2.0
    minimum_points: 10
  trailing_stop:
    enabled: true
    activation_threshold: 0.01  # 1% profit
    trail_percent: 0.005       # 0.5% trail

signal:
  confidence_threshold: 0.7
  minimum_signal_strength: 0.5
  indicators:
    rsi:
      window: 14
      overbought: 70
      oversold: 30
    macd:
      fast_period: 12
      slow_period: 26
      signal_period: 9
    bollinger:
      window: 20
      num_std: 2
    atr:
      window: 14

performance:
  metrics_update_interval: 60  # seconds
  position_update_interval: 5  # seconds
  save_interval: 3600         # hourly saves

logging:
  level: INFO
  file_rotation: 5
  max_file_size: 10485760  # 10MB
  performance_tracking: true
  log_trades: true
  log_signals: true

# development.yaml (overrides for development)
database:
  path: "data/market_data_dev.db"

logging:
  level: DEBUG
  
risk:
  max_risk_per_trade: 0.01  # More conservative for development

# production.yaml (overrides for production)
logging:
  level: WARNING
  file_rotation: 10
  max_file_size: 52428800  # 50MB